name: 🚀 Feature request
description: Suggest a new idea or improvement for the project.
title: 🚀[Feature] Enter a title
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        📝 **Use the title field above to provide a clear, concise title**, for example: 🚀[Feature] Add support for a new live platform.
  - type: checkboxes
    attributes:
      label: ⚠️ Search for similar issues
      description: >
        🔍 [Search existing issues](https://github.com/ihmily/StreamCap/issues?q=is%3Aissue) with relevant keywords to avoid duplicates.
      options:
        - label: I have searched existing issues and found no similar request.
          required: true
  - type: textarea
    attributes:
      label: 📜 Feature description
      description: Describe the feature you want, including how it should work and the expected result.
      placeholder: |
        Feature description:
  - type: textarea
    attributes:
      label: 🌐 Example (optional)
      description: If possible, provide examples, screenshots, or related URLs.
      placeholder: |
        Example stream URL:
        `https://www.example.com/live/xxxx`
  - type: textarea
    attributes:
      label: 💡 Motivation
      description: Explain why you need this feature and what limitation it solves.
      placeholder: |
        I need this feature because...
