from ....utils.logger import logger
from .base import PlatformHandler, StreamData
from .handlers import (
    AcfunHandler,
    BaiduHandler,
    BigoHandler,
    BilibiliHandler,
    BluedHandler,
    ChangliaoHandler,
    ChzzkHandler,
    CustomHandler,
    DouyinHandler,
    DouyuHandler,
    FaceitHandler,
    FlexTVHandler,
    HaixiuHandler,
    HuajiaoHandler,
    HuamaoHandler,
    HuyaHandler,
    InkeHandler,
    JDHandler,
    KuaishouHandler,
    KugouHandler,
    LaixiuHandler,
    LangLiveHandler,
    LehaiHandler,
    LianJieHandler,
    LivemeHandler,
    LookHandler,
    MaoerFMHandler,
    MiguHandler,
    NeteaseHandler,
    PamdaTVHandler,
    PiaopiaoHandler,
    PicartoHandler,
    PopkonTVHandler,
    QiandureboHandler,
    RedNoteHandler,
    ShopeeHandler,
    ShowRoomHandlerHandler,
    SixRoomHandler,
    SoopHandler,
    TaobaoHandler,
    TikTokHandler,
    TwitcastingHandler,
    TwitchHandler,
    VVXQHandler,
    WeiboHandler,
    WinkTVHandler,
    YinboHandler,
    YiqiLiveHandler,
    YoutubeHandler,
    YYHandler,
    ZhihuHandler,
)


def get_platform_handler(
    live_url: str,
    proxy: str | None = None,
    cookies: dict | str | None = None,
    record_quality: str = "default",
    platform: str | None = None,
    username: str | None = None,
    password: str | None = None,
    account_type: str | None = None,
) -> PlatformHandler | None:
    handler_instance = PlatformHandler.get_handler_instance(
        live_url, proxy, cookies, record_quality, platform, username, password, account_type
    )
    if handler_instance:
        return handler_instance
    logger.warning(f"Unknown live platform: {live_url}")
    return None


def get_platform_info(record_url: str) -> tuple:
    platform_map = {
        "douyin.com/": ("Douyin Live", "douyin"),
        "tiktok.com/": ("TikTok Live", "tiktok"),
        "https://live.kuaishou.com/": ("Kuaishou Live", "kuaishou"),
        "https://www.huya.com/": ("Huya Live", "huya"),
        "https://www.douyu.com/": ("Douyu Live", "douyu"),
        "https://www.yy.com/": ("YY Live", "yy"),
        "https://live.bilibili.com/": ("Bilibili Live", "bilibili"),
        "https://www.xiaohongshu.com/": ("Rednote Live", "xiaohongshu"),
        "xhslink.com/": ("Rednote Live", "xhs"),
        "https://www.bigo.tv/": ("Bigo Live", "bigo"),
        "https://app.blued.cn/": ("Blued Live", "blued"),
        "sooplive.co.kr/": ("SOOP", "sooplive"),
        "www.sooplive.com/": ("SOOP", "sooplive"),
        "cc.163.com/": ("Netease CC Live", "netease"),
        "qiandurebo.com/": ("Qiandurebo Live", "qiandurebo"),
        "pandalive.co.kr/": ("PandaTV", "pandalive"),
        "fm.missevan.com/": ("MaoerFM Live", "maoerfm"),
        "winktv.co.kr/": ("WinkTV", "winktv"),
        "flextv.co.kr/": ("FlexTV", "flextv"),
        "ttinglive.com/": ("FlexTV", "flextv"),
        "look.163.com/": ("Look Live", "look"),
        "popkontv.com/": ("PopkonTV", "popkontv"),
        "twitcasting.tv/": ("TwitCasting", "twitcasting"),
        "live.baidu.com/": ("Baidu Live", "baidu"),
        "weibo.com/": ("Weibo Live", "weibo"),
        "kugou.com/": ("Kugou Live", "kugou"),
        "twitch.tv/": ("TwitchTV", "twitch"),
        "liveme.com/": ("LiveMe", "liveme"),
        "huajiao.com/": ("Huajiao Live", "huajiao"),
        "7u66.com/": ("Liuxing Live", "liuxing"),
        "showroom-live.com/": ("ShowRoom", "showroom"),
        "live.acfun.cn/": ("Acfun", "acfun"),
        "tlclw.com/": ("Changliao Live", "changliao"),
        "ybw1666.com/": ("Yinbo Live", "yingbo"),
        "inke.cn/": ("Inke Live", "inke"),
        "zhihu.com/": ("Zhihu Live", "zhihu"),
        "chzzk.naver.com/": ("CHZZK", "chzzk"),
        "haixiutv.com/": ("Haixiu Live", "haixiu"),
        "vvxqiu.com/": ("VVXqiu Live", "vvxq"),
        "17.live/": ("17Live", "17live"),
        "lang.live/": ("Lang Live", "lang"),
        "m.pp.weimipopo.com/": ("Piaopiao Live", "piaopiao"),
        ".6.cn/": ("6rooms Live", "6room"),
        "lehaitv.com/": ("Lehai Live", "lehai"),
        "h.catshow168.com/": ("Catshow Live", "catshow"),
        "live.shopee": ("shopee", "shopee"),
        ".shp.": ("shopee", "shopee"),
        "youtube.com/": ("Youtube", "youtube"),
        "tb.cn": ("Taobao Live", "taobao"),
        "tbzb.taobao.com": ("Taobao Live", "taobao"),
        "3.cn": ("JD Live", "jd"),
        "faceit.com": ("faceit", "faceit"),
        "lailianjie.com": ("Lianjie Live", "lianjie"),
        "miguvideo.com": ("Migu Live", "migu"),
        "imkktv.com": ("Laixiu Live", "laixiu"),
        "picarto.tv": ("Picarto", "picarto"),
        ".m3u8": ("Custom Live Recording", "custom"),
        ".flv": ("Custom Live Recording", "custom"),
    }

    for key, value in platform_map.items():
        if key in record_url:
            return value[0], value[1]

    return None, None


__all__ = [
    "AcfunHandler",
    "BaiduHandler",
    "BigoHandler",
    "BilibiliHandler",
    "BluedHandler",
    "ChangliaoHandler",
    "ChzzkHandler",
    "CustomHandler",
    "DouyinHandler",
    "DouyuHandler",
    "FaceitHandler",
    "FlexTVHandler",
    "HaixiuHandler",
    "HuajiaoHandler",
    "HuamaoHandler",
    "HuyaHandler",
    "InkeHandler",
    "JDHandler",
    "KuaishouHandler",
    "KugouHandler",
    "LaixiuHandler",
    "LangLiveHandler",
    "LehaiHandler",
    "LianJieHandler",
    "LivemeHandler",
    "LookHandler",
    "MaoerFMHandler",
    "MiguHandler",
    "NeteaseHandler",
    "PamdaTVHandler",
    "PiaopiaoHandler",
    "PicartoHandler",
    "PlatformHandler",
    "PopkonTVHandler",
    "QiandureboHandler",
    "RedNoteHandler",
    "ShopeeHandler",
    "ShowRoomHandlerHandler",
    "SixRoomHandler",
    "SoopHandler",
    "StreamData",
    "TaobaoHandler",
    "TikTokHandler",
    "TwitcastingHandler",
    "TwitchHandler",
    "VVXQHandler",
    "WeiboHandler",
    "WinkTVHandler",
    "YYHandler",
    "YinboHandler",
    "YiqiLiveHandler",
    "YoutubeHandler",
    "ZhihuHandler",
    "get_platform_handler",
    "get_platform_info",
]
